const { Success } = require("../utils");

const apiResponse = async (req, res) => {
  const { question } = req.body;
  return res.status(200).json(
    Success("Answer generated...", null, {
      question: question,
      summary: "This is the summary of the simulated answer generated by the AI.",
      result_text: "This is the simulated result generated to the given question",
      result_table_path: "https://example.com/tables/sales_growth_q1_2024",
      result_visualization_path:
        "https://example.com/visuals/sales_growth_q1_2024_chart",
      error: "Simulated error",
    })
  );
};

module.exports = { apiResponse };
